wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.34.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696604146.744855
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.15.9
      6: 4.34.0.dev0
      8:
      - 5
